### ISSUE TITLE
Object model and Class diagram

### ISSUE THREAD

**Issue by furkansahin** [CrypDist/Reports#4]
Tbh. I saw this header in my OOP Analysis report but I don't really get to know how we can manage to decide on class diagram in this stage... To be more clear, I suggest we should contact to Mehmet Gok and first understand the cloud architecture we will use <i>(we can ask for the demo account and start to monkey with the api)</i> and then we need to think about the blockchain structure we will create, too. To understand blockchain structure, we first need to search ourselves <i>(if you have any resource that you think useful share it below plz)</i> and then we can reach to https://www.facebook.com/halilozercan for further questions as @calkan suggested.
- https://news.ycombinator.com/item?id=9436847 
- https://www.ethereum.org (an interesting project, just like ours :D )

**Comment by oguzdemir** [comment]
For the analysis, just mentioned the basic parts of the project and did not go in very technical details, such as BlockChain implementation. 

https://github.com/CrypDist/Reports/pull/5
